services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flutter_golang_tchat_db
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    depends_on:
      - postgres