migrateup:
	 migrate -path db/migrations -database "postgres://postgres:postgres@localhost:5432/flutter_golang_tchat_db?sslmode=disable" -verbose up
migratedown:
	 migrate -path db/migrations -database "postgres://postgres:postgres@localhost:5432/flutter_golang_tchat_db?sslmode=disable" -verbose down